//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZDL.EFDbFirst.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Z_Goods
    {
        [Key]
        public int id { get; set; }
        public string barcode { get; set; }
        public int goodsType { get; set; }
        public string name { get; set; }
        public bool isAudit { get; set; }
        public bool isEnabled { get; set; }       
    }
}
