//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZDL.EFDbFirst.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Z_GoodsOrder
    {
        [Key]
        public int order_id { get; set; }
        public int goods_id { get; set; }
        public string buyer { get; set; }
        public System.DateTime buy_time { get; set; } 
    }
}
